FROM node:20-alpine

RUN apk add --no-cache docker-cli

WORKDIR /app

COPY docker-manager.js package-docker-manager.json ./
RUN mv package-docker-manager.json package.json && npm install --production

EXPOSE 8081

CMD ["node", "docker-manager.js"]
