services:
  ollama:
    image: ollama/ollama
    container_name: cloudpc-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/ollama serve &
        sleep 5
        ollama pull llama3.2
        wait
    networks:
      - cloudpc-net
    restart: always

networks:
  cloudpc-net:
    name: cloudpc-net
    driver: bridge

volumes:
  ollama_models:
    name: cloudpc-ollama-models
