({
  setup() {
    const { ref, computed, onMounted, onUnmounted } = Vue;

    // ── Unit definitions ──
    const CATEGORIES = [
      { key:'length', icon:'📏' },
      { key:'weight', icon:'⚖️' },
      { key:'temperature', icon:'🌡️' },
      { key:'area', icon:'📐' },
      { key:'volume', icon:'🧪' },
      { key:'speed', icon:'🚀' },
      { key:'time', icon:'⏱️' },
      { key:'data', icon:'💾' },
      { key:'pressure', icon:'🔧' },
      { key:'energy', icon:'⚡' }
    ];

    // factor = multiply by this to convert to base unit
    const UNIT_DEFS = {
      length: {
        base: 'm',
        units: [
          { key:'mm', symbol:'mm', factor:0.001 },
          { key:'cm', symbol:'cm', factor:0.01 },
          { key:'m', symbol:'m', factor:1 },
          { key:'km', symbol:'km', factor:1000 },
          { key:'inch', symbol:'in', factor:0.0254 },
          { key:'foot', symbol:'ft', factor:0.3048 },
          { key:'yard', symbol:'yd', factor:0.9144 },
          { key:'mile', symbol:'mi', factor:1609.344 },
          { key:'nautical_mile', symbol:'nmi', factor:1852 }
        ]
      },
      weight: {
        base: 'kg',
        units: [
          { key:'mg', symbol:'mg', factor:0.000001 },
          { key:'g', symbol:'g', factor:0.001 },
          { key:'kg', symbol:'kg', factor:1 },
          { key:'ton', symbol:'t', factor:1000 },
          { key:'ounce', symbol:'oz', factor:0.0283495 },
          { key:'pound', symbol:'lb', factor:0.453592 },
          { key:'stone', symbol:'st', factor:6.35029 }
        ]
      },
      temperature: {
        base: 'celsius',
        units: [
          { key:'celsius', symbol:'°C', factor:null },
          { key:'fahrenheit', symbol:'°F', factor:null },
          { key:'kelvin', symbol:'K', factor:null }
        ]
      },
      area: {
        base: 'sqm',
        units: [
          { key:'sqmm', symbol:'mm²', factor:0.000001 },
          { key:'sqcm', symbol:'cm²', factor:0.0001 },
          { key:'sqm', symbol:'m²', factor:1 },
          { key:'hectare', symbol:'ha', factor:10000 },
          { key:'sqkm', symbol:'km²', factor:1000000 },
          { key:'sqinch', symbol:'in²', factor:0.00064516 },
          { key:'sqfoot', symbol:'ft²', factor:0.092903 },
          { key:'acre', symbol:'ac', factor:4046.86 },
          { key:'sqmile', symbol:'mi²', factor:2589988.11 }
        ]
      },
      volume: {
        base: 'liter',
        units: [
          { key:'ml', symbol:'mL', factor:0.001 },
          { key:'liter', symbol:'L', factor:1 },
          { key:'cubicm', symbol:'m³', factor:1000 },
          { key:'gallon_us', symbol:'gal(US)', factor:3.78541 },
          { key:'gallon_uk', symbol:'gal(UK)', factor:4.54609 },
          { key:'quart', symbol:'qt', factor:0.946353 },
          { key:'pint', symbol:'pt', factor:0.473176 },
          { key:'cup', symbol:'cup', factor:0.236588 },
          { key:'floz', symbol:'fl oz', factor:0.0295735 }
        ]
      },
      speed: {
        base: 'mps',
        units: [
          { key:'mps', symbol:'m/s', factor:1 },
          { key:'kmh', symbol:'km/h', factor:0.277778 },
          { key:'mph', symbol:'mph', factor:0.44704 },
          { key:'knot', symbol:'kn', factor:0.514444 },
          { key:'fps', symbol:'ft/s', factor:0.3048 }
        ]
      },
      time: {
        base: 'second',
        units: [
          { key:'ms', symbol:'ms', factor:0.001 },
          { key:'second', symbol:'s', factor:1 },
          { key:'minute', symbol:'min', factor:60 },
          { key:'hour', symbol:'h', factor:3600 },
          { key:'day', symbol:'d', factor:86400 },
          { key:'week', symbol:'wk', factor:604800 },
          { key:'month', symbol:'mo', factor:2592000 },
          { key:'year', symbol:'yr', factor:31536000 }
        ]
      },
      data: {
        base: 'byte',
        units: [
          { key:'bit', symbol:'b', factor:0.125 },
          { key:'byte', symbol:'B', factor:1 },
          { key:'kb', symbol:'KB', factor:1024 },
          { key:'mb', symbol:'MB', factor:1048576 },
          { key:'gb', symbol:'GB', factor:1073741824 },
          { key:'tb', symbol:'TB', factor:1099511627776 }
        ]
      },
      pressure: {
        base: 'pascal',
        units: [
          { key:'pascal', symbol:'Pa', factor:1 },
          { key:'kpa', symbol:'kPa', factor:1000 },
          { key:'bar', symbol:'bar', factor:100000 },
          { key:'atm', symbol:'atm', factor:101325 },
          { key:'psi', symbol:'psi', factor:6894.76 },
          { key:'mmhg', symbol:'mmHg', factor:133.322 }
        ]
      },
      energy: {
        base: 'joule',
        units: [
          { key:'joule', symbol:'J', factor:1 },
          { key:'kj', symbol:'kJ', factor:1000 },
          { key:'calorie', symbol:'cal', factor:4.184 },
          { key:'kcal', symbol:'kcal', factor:4184 },
          { key:'wh', symbol:'Wh', factor:3600 },
          { key:'kwh', symbol:'kWh', factor:3600000 },
          { key:'btu', symbol:'BTU', factor:1055.06 }
        ]
      }
    };

    // ── i18n ──
    const LANGS = {
      tr: {
        title:'Birim Dönüştürücü',
        category:'Kategori',
        from:'Kaynak',
        to:'Hedef',
        selectUnit:'Birim seç',
        formula:'Formül',
        quickRef:'Hızlı Referans',
        cancel:'İptal',
        cat_length:'Uzunluk',
        cat_weight:'Ağırlık',
        cat_temperature:'Sıcaklık',
        cat_area:'Alan',
        cat_volume:'Hacim',
        cat_speed:'Hız',
        cat_time:'Zaman',
        cat_data:'Veri',
        cat_pressure:'Basınç',
        cat_energy:'Enerji',
        unit_mm:'Milimetre',
        unit_cm:'Santimetre',
        unit_m:'Metre',
        unit_km:'Kilometre',
        unit_inch:'İnç',
        unit_foot:'Feet',
        unit_yard:'Yarda',
        unit_mile:'Mil',
        unit_nautical_mile:'Deniz Mili',
        unit_mg:'Miligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Ton',
        unit_ounce:'Ons',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Santigrat',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hektar',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Dönüm(Acre)',
        unit_sqmile:'mi²',
        unit_ml:'Mililitre',
        unit_liter:'Litre',
        unit_cubicm:'m³',
        unit_gallon_us:'Galon(US)',
        unit_gallon_uk:'Galon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Fincan',
        unit_floz:'Sıvı Ons',
        unit_mps:'m/s',
        unit_kmh:'km/sa',
        unit_mph:'mil/sa',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Milisaniye',
        unit_second:'Saniye',
        unit_minute:'Dakika',
        unit_hour:'Saat',
        unit_day:'Gün',
        unit_week:'Hafta',
        unit_month:'Ay',
        unit_year:'Yıl',
        unit_bit:'Bit',
        unit_byte:'Bayt',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosfer',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Kalori',
        unit_kcal:'Kilokalori',
        unit_wh:'Watt-saat',
        unit_kwh:'Kilowatt-saat',
        unit_btu:'BTU'
      },
      en: {
        title:'Unit Converter',
        category:'Category',
        from:'From',
        to:'To',
        selectUnit:'Select unit',
        formula:'Formula',
        quickRef:'Quick Reference',
        cancel:'Cancel',
        cat_length:'Length',
        cat_weight:'Weight',
        cat_temperature:'Temperature',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Speed',
        cat_time:'Time',
        cat_data:'Data',
        cat_pressure:'Pressure',
        cat_energy:'Energy',
        unit_mm:'Millimeter',
        unit_cm:'Centimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Inch',
        unit_foot:'Foot',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Nautical Mile',
        unit_mg:'Milligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Metric Ton',
        unit_ounce:'Ounce',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Cup',
        unit_floz:'Fluid Ounce',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Millisecond',
        unit_second:'Second',
        unit_minute:'Minute',
        unit_hour:'Hour',
        unit_day:'Day',
        unit_week:'Week',
        unit_month:'Month',
        unit_year:'Year',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-hour',
        unit_kwh:'Kilowatt-hour',
        unit_btu:'BTU'
      },
      de: {
        title:'Einheitenrechner',
        category:'Kategorie',
        from:'Von',
        to:'Nach',
        selectUnit:'Einheit wählen',
        formula:'Formel',
        quickRef:'Kurzreferenz',
        cancel:'Abbrechen',
        cat_length:'Länge',
        cat_weight:'Gewicht',
        cat_temperature:'Temperatur',
        cat_area:'Fläche',
        cat_volume:'Volumen',
        cat_speed:'Geschwindigkeit',
        cat_time:'Zeit',
        cat_data:'Daten',
        cat_pressure:'Druck',
        cat_energy:'Energie',
        unit_mm:'Millimeter',
        unit_cm:'Zentimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Zoll',
        unit_foot:'Fuß',
        unit_yard:'Yard',
        unit_mile:'Meile',
        unit_nautical_mile:'Seemeile',
        unit_mg:'Milligramm',
        unit_g:'Gramm',
        unit_kg:'Kilogramm',
        unit_ton:'Tonne',
        unit_ounce:'Unze',
        unit_pound:'Pfund',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hektar',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallone(US)',
        unit_gallon_uk:'Gallone(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Tasse',
        unit_floz:'Flüssigunze',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knoten',
        unit_fps:'ft/s',
        unit_ms:'Millisekunde',
        unit_second:'Sekunde',
        unit_minute:'Minute',
        unit_hour:'Stunde',
        unit_day:'Tag',
        unit_week:'Woche',
        unit_month:'Monat',
        unit_year:'Jahr',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphäre',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Kalorie',
        unit_kcal:'Kilokalorie',
        unit_wh:'Wattstunde',
        unit_kwh:'Kilowattstunde',
        unit_btu:'BTU'
      },
      fr: {
        title:'Convertisseur d\'Unités',
        category:'Catégorie',
        from:'De',
        to:'Vers',
        selectUnit:'Choisir unité',
        formula:'Formule',
        quickRef:'Référence Rapide',
        cancel:'Annuler',
        cat_length:'Longueur',
        cat_weight:'Poids',
        cat_temperature:'Température',
        cat_area:'Surface',
        cat_volume:'Volume',
        cat_speed:'Vitesse',
        cat_time:'Temps',
        cat_data:'Données',
        cat_pressure:'Pression',
        cat_energy:'Énergie',
        unit_mm:'Millimètre',
        unit_cm:'Centimètre',
        unit_m:'Mètre',
        unit_km:'Kilomètre',
        unit_inch:'Pouce',
        unit_foot:'Pied',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Mille Marin',
        unit_mg:'Milligramme',
        unit_g:'Gramme',
        unit_kg:'Kilogramme',
        unit_ton:'Tonne',
        unit_ounce:'Once',
        unit_pound:'Livre',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Millilitre',
        unit_liter:'Litre',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pinte',
        unit_cup:'Tasse',
        unit_floz:'Once Liquide',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Nœud',
        unit_fps:'ft/s',
        unit_ms:'Milliseconde',
        unit_second:'Seconde',
        unit_minute:'Minute',
        unit_hour:'Heure',
        unit_day:'Jour',
        unit_week:'Semaine',
        unit_month:'Mois',
        unit_year:'Année',
        unit_bit:'Bit',
        unit_byte:'Octet',
        unit_kb:'Ko',
        unit_mb:'Mo',
        unit_gb:'Go',
        unit_tb:'To',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphère',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-heure',
        unit_kwh:'Kilowatt-heure',
        unit_btu:'BTU'
      },
      es: {
        title:'Conversor de Unidades',
        category:'Categoría',
        from:'De',
        to:'A',
        selectUnit:'Seleccionar unidad',
        formula:'Fórmula',
        quickRef:'Referencia Rápida',
        cancel:'Cancelar',
        cat_length:'Longitud',
        cat_weight:'Peso',
        cat_temperature:'Temperatura',
        cat_area:'Área',
        cat_volume:'Volumen',
        cat_speed:'Velocidad',
        cat_time:'Tiempo',
        cat_data:'Datos',
        cat_pressure:'Presión',
        cat_energy:'Energía',
        unit_mm:'Milímetro',
        unit_cm:'Centímetro',
        unit_m:'Metro',
        unit_km:'Kilómetro',
        unit_inch:'Pulgada',
        unit_foot:'Pie',
        unit_yard:'Yarda',
        unit_mile:'Milla',
        unit_nautical_mile:'Milla Náutica',
        unit_mg:'Miligramo',
        unit_g:'Gramo',
        unit_kg:'Kilogramo',
        unit_ton:'Tonelada',
        unit_ounce:'Onza',
        unit_pound:'Libra',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectárea',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Mililitro',
        unit_liter:'Litro',
        unit_cubicm:'m³',
        unit_gallon_us:'Galón(US)',
        unit_gallon_uk:'Galón(UK)',
        unit_quart:'Cuarto',
        unit_pint:'Pinta',
        unit_cup:'Taza',
        unit_floz:'Onza Líquida',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Nudo',
        unit_fps:'ft/s',
        unit_ms:'Milisegundo',
        unit_second:'Segundo',
        unit_minute:'Minuto',
        unit_hour:'Hora',
        unit_day:'Día',
        unit_week:'Semana',
        unit_month:'Mes',
        unit_year:'Año',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmósfera',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Julio',
        unit_kj:'Kilojulio',
        unit_calorie:'Caloría',
        unit_kcal:'Kilocaloría',
        unit_wh:'Vatio-hora',
        unit_kwh:'Kilovatio-hora',
        unit_btu:'BTU'
      },
      ru: {
        title:'Конвертер Единиц',
        category:'Категория',
        from:'Из',
        to:'В',
        selectUnit:'Выберите единицу',
        formula:'Формула',
        quickRef:'Справка',
        cancel:'Отмена',
        cat_length:'Длина',
        cat_weight:'Вес',
        cat_temperature:'Температура',
        cat_area:'Площадь',
        cat_volume:'Объём',
        cat_speed:'Скорость',
        cat_time:'Время',
        cat_data:'Данные',
        cat_pressure:'Давление',
        cat_energy:'Энергия',
        unit_mm:'Миллиметр',
        unit_cm:'Сантиметр',
        unit_m:'Метр',
        unit_km:'Километр',
        unit_inch:'Дюйм',
        unit_foot:'Фут',
        unit_yard:'Ярд',
        unit_mile:'Миля',
        unit_nautical_mile:'Морская Миля',
        unit_mg:'Миллиграмм',
        unit_g:'Грамм',
        unit_kg:'Килограмм',
        unit_ton:'Тонна',
        unit_ounce:'Унция',
        unit_pound:'Фунт',
        unit_stone:'Стоун',
        unit_celsius:'Цельсий',
        unit_fahrenheit:'Фаренгейт',
        unit_kelvin:'Кельвин',
        unit_sqmm:'мм²',
        unit_sqcm:'см²',
        unit_sqm:'м²',
        unit_hectare:'Гектар',
        unit_sqkm:'км²',
        unit_sqinch:'дюйм²',
        unit_sqfoot:'фут²',
        unit_acre:'Акр',
        unit_sqmile:'миля²',
        unit_ml:'Миллилитр',
        unit_liter:'Литр',
        unit_cubicm:'м³',
        unit_gallon_us:'Галлон(US)',
        unit_gallon_uk:'Галлон(UK)',
        unit_quart:'Кварта',
        unit_pint:'Пинта',
        unit_cup:'Чашка',
        unit_floz:'Жидкая Унция',
        unit_mps:'м/с',
        unit_kmh:'км/ч',
        unit_mph:'миль/ч',
        unit_knot:'Узел',
        unit_fps:'фут/с',
        unit_ms:'Миллисекунда',
        unit_second:'Секунда',
        unit_minute:'Минута',
        unit_hour:'Час',
        unit_day:'День',
        unit_week:'Неделя',
        unit_month:'Месяц',
        unit_year:'Год',
        unit_bit:'Бит',
        unit_byte:'Байт',
        unit_kb:'КБ',
        unit_mb:'МБ',
        unit_gb:'ГБ',
        unit_tb:'ТБ',
        unit_pascal:'Паскаль',
        unit_kpa:'Килопаскаль',
        unit_bar:'Бар',
        unit_atm:'Атмосфера',
        unit_psi:'PSI',
        unit_mmhg:'мм рт.ст.',
        unit_joule:'Джоуль',
        unit_kj:'Килоджоуль',
        unit_calorie:'Калория',
        unit_kcal:'Килокалория',
        unit_wh:'Ватт-час',
        unit_kwh:'Киловатт-час',
        unit_btu:'BTU'
      },
      zh: {
        title:'单位转换器',
        category:'类别',
        from:'从',
        to:'到',
        selectUnit:'选择单位',
        formula:'公式',
        quickRef:'快速参考',
        cancel:'关闭',
        cat_length:'长度',
        cat_weight:'重量',
        cat_temperature:'温度',
        cat_area:'面积',
        cat_volume:'体积',
        cat_speed:'速度',
        cat_time:'时间',
        cat_data:'数据',
        cat_pressure:'压力',
        cat_energy:'能量',
        unit_mm:'毫米',
        unit_cm:'厘米',
        unit_m:'米',
        unit_km:'千米',
        unit_inch:'英寸',
        unit_foot:'英尺',
        unit_yard:'码',
        unit_mile:'英里',
        unit_nautical_mile:'海里',
        unit_mg:'毫克',
        unit_g:'克',
        unit_kg:'千克',
        unit_ton:'吨',
        unit_ounce:'盎司',
        unit_pound:'磅',
        unit_stone:'英石',
        unit_celsius:'摄氏度',
        unit_fahrenheit:'华氏度',
        unit_kelvin:'开尔文',
        unit_sqmm:'平方毫米',
        unit_sqcm:'平方厘米',
        unit_sqm:'平方米',
        unit_hectare:'公顷',
        unit_sqkm:'平方千米',
        unit_sqinch:'平方英寸',
        unit_sqfoot:'平方英尺',
        unit_acre:'英亩',
        unit_sqmile:'平方英里',
        unit_ml:'毫升',
        unit_liter:'升',
        unit_cubicm:'立方米',
        unit_gallon_us:'美制加仑',
        unit_gallon_uk:'英制加仑',
        unit_quart:'夸脱',
        unit_pint:'品脱',
        unit_cup:'杯',
        unit_floz:'液量盎司',
        unit_mps:'米/秒',
        unit_kmh:'千米/时',
        unit_mph:'英里/时',
        unit_knot:'节',
        unit_fps:'英尺/秒',
        unit_ms:'毫秒',
        unit_second:'秒',
        unit_minute:'分钟',
        unit_hour:'小时',
        unit_day:'天',
        unit_week:'周',
        unit_month:'月',
        unit_year:'年',
        unit_bit:'比特',
        unit_byte:'字节',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'帕斯卡',
        unit_kpa:'千帕',
        unit_bar:'巴',
        unit_atm:'标准大气压',
        unit_psi:'磅/平方英寸',
        unit_mmhg:'毫米汞柱',
        unit_joule:'焦耳',
        unit_kj:'千焦',
        unit_calorie:'卡路里',
        unit_kcal:'千卡',
        unit_wh:'瓦时',
        unit_kwh:'千瓦时',
        unit_btu:'英热单位'
      },
      ja: {
        title:'単位変換',
        category:'カテゴリ',
        from:'変換元',
        to:'変換先',
        selectUnit:'単位を選択',
        formula:'計算式',
        quickRef:'クイックリファレンス',
        cancel:'閉じる',
        cat_length:'長さ',
        cat_weight:'重さ',
        cat_temperature:'温度',
        cat_area:'面積',
        cat_volume:'体積',
        cat_speed:'速度',
        cat_time:'時間',
        cat_data:'データ',
        cat_pressure:'圧力',
        cat_energy:'エネルギー',
        unit_mm:'ミリメートル',
        unit_cm:'センチメートル',
        unit_m:'メートル',
        unit_km:'キロメートル',
        unit_inch:'インチ',
        unit_foot:'フィート',
        unit_yard:'ヤード',
        unit_mile:'マイル',
        unit_nautical_mile:'海里',
        unit_mg:'ミリグラム',
        unit_g:'グラム',
        unit_kg:'キログラム',
        unit_ton:'トン',
        unit_ounce:'オンス',
        unit_pound:'ポンド',
        unit_stone:'ストーン',
        unit_celsius:'摂氏',
        unit_fahrenheit:'華氏',
        unit_kelvin:'ケルビン',
        unit_sqmm:'平方ミリ',
        unit_sqcm:'平方センチ',
        unit_sqm:'平方メートル',
        unit_hectare:'ヘクタール',
        unit_sqkm:'平方キロ',
        unit_sqinch:'平方インチ',
        unit_sqfoot:'平方フィート',
        unit_acre:'エーカー',
        unit_sqmile:'平方マイル',
        unit_ml:'ミリリットル',
        unit_liter:'リットル',
        unit_cubicm:'立方メートル',
        unit_gallon_us:'米ガロン',
        unit_gallon_uk:'英ガロン',
        unit_quart:'クォート',
        unit_pint:'パイント',
        unit_cup:'カップ',
        unit_floz:'液量オンス',
        unit_mps:'メートル/秒',
        unit_kmh:'キロ/時',
        unit_mph:'マイル/時',
        unit_knot:'ノット',
        unit_fps:'フィート/秒',
        unit_ms:'ミリ秒',
        unit_second:'秒',
        unit_minute:'分',
        unit_hour:'時間',
        unit_day:'日',
        unit_week:'週',
        unit_month:'月',
        unit_year:'年',
        unit_bit:'ビット',
        unit_byte:'バイト',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'パスカル',
        unit_kpa:'キロパスカル',
        unit_bar:'バール',
        unit_atm:'気圧',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'ジュール',
        unit_kj:'キロジュール',
        unit_calorie:'カロリー',
        unit_kcal:'キロカロリー',
        unit_wh:'ワット時',
        unit_kwh:'キロワット時',
        unit_btu:'BTU'
      },
      it: {
        title:'Convertitore Unità',
        category:'Categoria',
        from:'Da',
        to:'A',
        selectUnit:'Seleziona unità',
        formula:'Formula',
        quickRef:'Riferimento rapido',
        cancel:'Chiudi',
        cat_length:'Lunghezza',
        cat_weight:'Peso',
        cat_temperature:'Temperatura',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Velocità',
        cat_time:'Tempo',
        cat_data:'Dati',
        cat_pressure:'Pressione',
        cat_energy:'Energia',
        unit_mm:'Millimetri',
        unit_cm:'Centimetri',
        unit_m:'Metri',
        unit_km:'Chilometri',
        unit_inch:'Pollici',
        unit_foot:'Piedi',
        unit_yard:'Iarde',
        unit_mile:'Miglia',
        unit_nautical_mile:'Miglia nautiche',
        unit_mg:'Milligrammi',
        unit_g:'Grammi',
        unit_kg:'Chilogrammi',
        unit_ton:'Tonnellate',
        unit_ounce:'Once',
        unit_pound:'Libbre',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Ettari',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acri',
        unit_sqmile:'mi²',
        unit_ml:'Millilitri',
        unit_liter:'Litri',
        unit_cubicm:'m³',
        unit_gallon_us:'Galloni US',
        unit_gallon_uk:'Galloni UK',
        unit_quart:'Quarti',
        unit_pint:'Pinte',
        unit_cup:'Tazze',
        unit_floz:'Once liquide',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Nodi',
        unit_fps:'ft/s',
        unit_ms:'Millisecondi',
        unit_second:'Secondi',
        unit_minute:'Minuti',
        unit_hour:'Ore',
        unit_day:'Giorni',
        unit_week:'Settimane',
        unit_month:'Mesi',
        unit_year:'Anni',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosfere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Wattora',
        unit_kwh:'Kilowattora',
        unit_btu:'BTU'
      },
      ar: {
        title:'محول الوحدات',
        category:'الفئة',
        from:'من',
        to:'إلى',
        selectUnit:'Select unit',
        formula:'Formula',
        quickRef:'Quick Reference',
        cancel:'إلغاء',
        cat_length:'Length',
        cat_weight:'الوزن',
        cat_temperature:'Temperature',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Speed',
        cat_time:'الوقت',
        cat_data:'Data',
        cat_pressure:'Pressure',
        cat_energy:'Energy',
        unit_mm:'Millimeter',
        unit_cm:'Centimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Inch',
        unit_foot:'Foot',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Nautical Mile',
        unit_mg:'Milligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Metric Ton',
        unit_ounce:'Ounce',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Cup',
        unit_floz:'Fluid Ounce',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Millisecond',
        unit_second:'Second',
        unit_minute:'Minute',
        unit_hour:'Hour',
        unit_day:'Day',
        unit_week:'Week',
        unit_month:'Month',
        unit_year:'Year',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-hour',
        unit_kwh:'Kilowatt-hour',
        unit_btu:'BTU'
      },
      ko: {
        title:'단위 변환기',
        category:'분류',
        from:'변환 전',
        to:'변환 후',
        selectUnit:'Select unit',
        formula:'Formula',
        quickRef:'Quick Reference',
        cancel:'취소',
        cat_length:'Length',
        cat_weight:'체중',
        cat_temperature:'Temperature',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Speed',
        cat_time:'Time',
        cat_data:'Data',
        cat_pressure:'Pressure',
        cat_energy:'Energy',
        unit_mm:'Millimeter',
        unit_cm:'Centimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Inch',
        unit_foot:'Foot',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Nautical Mile',
        unit_mg:'Milligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Metric Ton',
        unit_ounce:'Ounce',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Cup',
        unit_floz:'Fluid Ounce',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Millisecond',
        unit_second:'Second',
        unit_minute:'Minute',
        unit_hour:'Hour',
        unit_day:'Day',
        unit_week:'Week',
        unit_month:'Month',
        unit_year:'Year',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-hour',
        unit_kwh:'Kilowatt-hour',
        unit_btu:'BTU'
      },
      hi: {
        title:'यूनिट कनवर्टर',
        category:'श्रेणी',
        from:'से',
        to:'में',
        selectUnit:'Select unit',
        formula:'Formula',
        quickRef:'Quick Reference',
        cancel:'रद्द करें',
        cat_length:'Length',
        cat_weight:'वजन',
        cat_temperature:'Temperature',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Speed',
        cat_time:'Time',
        cat_data:'Data',
        cat_pressure:'Pressure',
        cat_energy:'Energy',
        unit_mm:'Millimeter',
        unit_cm:'Centimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Inch',
        unit_foot:'Foot',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Nautical Mile',
        unit_mg:'Milligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Metric Ton',
        unit_ounce:'Ounce',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Cup',
        unit_floz:'Fluid Ounce',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Millisecond',
        unit_second:'Second',
        unit_minute:'Minute',
        unit_hour:'Hour',
        unit_day:'Day',
        unit_week:'Week',
        unit_month:'Month',
        unit_year:'Year',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-hour',
        unit_kwh:'Kilowatt-hour',
        unit_btu:'BTU'
      },
      pt: {
        title:'Conversor de Unidades',
        category:'Categoria',
        from:'De',
        to:'Para',
        selectUnit:'Select unit',
        formula:'Formula',
        quickRef:'Quick Reference',
        cancel:'Cancelar',
        cat_length:'Length',
        cat_weight:'Peso',
        cat_temperature:'Temperature',
        cat_area:'Area',
        cat_volume:'Volume',
        cat_speed:'Speed',
        cat_time:'Time',
        cat_data:'Data',
        cat_pressure:'Pressure',
        cat_energy:'Energy',
        unit_mm:'Millimeter',
        unit_cm:'Centimeter',
        unit_m:'Meter',
        unit_km:'Kilometer',
        unit_inch:'Inch',
        unit_foot:'Foot',
        unit_yard:'Yard',
        unit_mile:'Mile',
        unit_nautical_mile:'Nautical Mile',
        unit_mg:'Milligram',
        unit_g:'Gram',
        unit_kg:'Kilogram',
        unit_ton:'Metric Ton',
        unit_ounce:'Ounce',
        unit_pound:'Pound',
        unit_stone:'Stone',
        unit_celsius:'Celsius',
        unit_fahrenheit:'Fahrenheit',
        unit_kelvin:'Kelvin',
        unit_sqmm:'mm²',
        unit_sqcm:'cm²',
        unit_sqm:'m²',
        unit_hectare:'Hectare',
        unit_sqkm:'km²',
        unit_sqinch:'in²',
        unit_sqfoot:'ft²',
        unit_acre:'Acre',
        unit_sqmile:'mi²',
        unit_ml:'Milliliter',
        unit_liter:'Liter',
        unit_cubicm:'m³',
        unit_gallon_us:'Gallon(US)',
        unit_gallon_uk:'Gallon(UK)',
        unit_quart:'Quart',
        unit_pint:'Pint',
        unit_cup:'Cup',
        unit_floz:'Fluid Ounce',
        unit_mps:'m/s',
        unit_kmh:'km/h',
        unit_mph:'mph',
        unit_knot:'Knot',
        unit_fps:'ft/s',
        unit_ms:'Millisecond',
        unit_second:'Second',
        unit_minute:'Minute',
        unit_hour:'Hour',
        unit_day:'Day',
        unit_week:'Week',
        unit_month:'Month',
        unit_year:'Year',
        unit_bit:'Bit',
        unit_byte:'Byte',
        unit_kb:'KB',
        unit_mb:'MB',
        unit_gb:'GB',
        unit_tb:'TB',
        unit_pascal:'Pascal',
        unit_kpa:'Kilopascal',
        unit_bar:'Bar',
        unit_atm:'Atmosphere',
        unit_psi:'PSI',
        unit_mmhg:'mmHg',
        unit_joule:'Joule',
        unit_kj:'Kilojoule',
        unit_calorie:'Calorie',
        unit_kcal:'Kilocalorie',
        unit_wh:'Watt-hour',
        unit_kwh:'Kilowatt-hour',
        unit_btu:'BTU'
      }
  };

    function getLocale() { try { return localStorage.getItem('sys_locale') || 'tr'; } catch { return 'tr'; } }
    const locale = ref(getLocale());
    function L(k) { return (LANGS[locale.value] || LANGS.tr)[k] || LANGS.tr[k] || k; }

    function onLocaleChanged(e) { locale.value = e.detail || getLocale(); }

    // ── State ──
    const category = ref('length');
    const fromUnit = ref('');
    const toUnit = ref('');
    const fromValue = ref('');
    const toValue = ref('');
    const categories = CATEGORIES;

    const units = computed(() => {
      const def = UNIT_DEFS[category.value];
      return def ? def.units : [];
    });

    function onCategoryChange() {
      const u = units.value;
      fromUnit.value = u.length > 0 ? u[0].key : '';
      toUnit.value = u.length > 1 ? u[1].key : u.length > 0 ? u[0].key : '';
      fromValue.value = '';
      toValue.value = '';
    }

    // ── Conversion ──
    function convertTemp(val, from, to) {
      let c;
      if (from === 'celsius') c = val;
      else if (from === 'fahrenheit') c = (val - 32) * 5 / 9;
      else c = val - 273.15; // kelvin
      if (to === 'celsius') return c;
      if (to === 'fahrenheit') return c * 9 / 5 + 32;
      return c + 273.15; // kelvin
    }

    function convert(val, from, to, cat) {
      if (!val && val !== 0) return '';
      const v = parseFloat(val);
      if (isNaN(v)) return '';
      if (from === to) return formatNum(v);

      if (cat === 'temperature') return formatNum(convertTemp(v, from, to));

      const def = UNIT_DEFS[cat];
      if (!def) return '';
      const fromDef = def.units.find(u => u.key === from);
      const toDef = def.units.find(u => u.key === to);
      if (!fromDef || !toDef) return '';
      const base = v * fromDef.factor;
      return formatNum(base / toDef.factor);
    }

    function formatNum(n) {
      if (Number.isInteger(n)) return String(n);
      const abs = Math.abs(n);
      if (abs >= 1) return n.toFixed(6).replace(/\.?0+$/, '');
      if (abs >= 0.0001) return n.toFixed(8).replace(/\.?0+$/, '');
      return n.toExponential(4);
    }

    function convertFromTo() {
      toValue.value = convert(fromValue.value, fromUnit.value, toUnit.value, category.value);
    }

    function swapUnits() {
      const tmpU = fromUnit.value;
      const tmpV = fromValue.value;
      fromUnit.value = toUnit.value;
      toUnit.value = tmpU;
      fromValue.value = toValue.value;
      toValue.value = tmpV ? convert(toValue.value, fromUnit.value, toUnit.value, category.value) : '';
    }

    // ── Formula display ──
    const formulaText = computed(() => {
      if (!fromUnit.value || !toUnit.value || fromUnit.value === toUnit.value) return '';
      const cat = category.value;
      if (cat === 'temperature') {
        const f = fromUnit.value, t = toUnit.value;
        if (f === 'celsius' && t === 'fahrenheit') return '°F = °C × 9/5 + 32';
        if (f === 'fahrenheit' && t === 'celsius') return '°C = (°F − 32) × 5/9';
        if (f === 'celsius' && t === 'kelvin') return 'K = °C + 273.15';
        if (f === 'kelvin' && t === 'celsius') return '°C = K − 273.15';
        if (f === 'fahrenheit' && t === 'kelvin') return 'K = (°F − 32) × 5/9 + 273.15';
        if (f === 'kelvin' && t === 'fahrenheit') return '°F = (K − 273.15) × 9/5 + 32';
        return '';
      }
      const def = UNIT_DEFS[cat];
      if (!def) return '';
      const fd = def.units.find(u => u.key === fromUnit.value);
      const td = def.units.find(u => u.key === toUnit.value);
      if (!fd || !td) return '';
      const ratio = fd.factor / td.factor;
      return '1 ' + fd.symbol + ' = ' + formatNum(ratio) + ' ' + td.symbol;
    });

    // ── Quick reference ──
    const refTable = computed(() => {
      if (!fromUnit.value || !toUnit.value) return [];
      const vals = [1, 5, 10, 50, 100, 500, 1000];
      const cat = category.value;
      const fd = UNIT_DEFS[cat] && UNIT_DEFS[cat].units.find(u => u.key === fromUnit.value);
      const td = UNIT_DEFS[cat] && UNIT_DEFS[cat].units.find(u => u.key === toUnit.value);
      if (!fd || !td) return [];
      return vals.map(v => ({
        val: v,
        from: v + ' ' + fd.symbol,
        to: convert(v, fromUnit.value, toUnit.value, cat) + ' ' + td.symbol
      }));
    });

    onMounted(() => {
      onCategoryChange();
      window.addEventListener('locale-changed', onLocaleChanged);
    });
    onUnmounted(() => { window.removeEventListener('locale-changed', onLocaleChanged); });

    return {
      category, fromUnit, toUnit, fromValue, toValue, categories, units,
      onCategoryChange, convertFromTo, swapUnits,
      formulaText, refTable, L
    };
  }
})
