({
  setup() {
    const { ref, computed, watch, onMounted, onUnmounted, nextTick } = Vue;
    const ElMessage = (window.ElementPlus && window.ElementPlus.ElMessage) || { success(){}, error(){}, warning(){}, info(){} };
    const ElMessageBox = (window.ElementPlus && window.ElementPlus.ElMessageBox) || { confirm: () => Promise.resolve() };

    /* ── i18n ── */
    const LANGS = {
      tr: {
        title:'Torrent',
        addTorrent:'Torrent Ekle',
        magnetLink:'Magnet Bağlantısı',
        torrentFile:'.torrent Dosyası',
        add:'Ekle',
        cancel:'İptal',
        pause:'Duraklat',
        resume:'Devam Et',
        remove:'Kaldır',
        removeData:'Verilerle birlikte sil',
        settings:'Ayarlar',
        name:'Ad',
        size:'Boyut',
        progress:'İlerleme',
        status:'Durum',
        downSpeed:'İndirme',
        upSpeed:'Yükleme',
        peers:'Eşler',
        seeds:'Seed',
        eta:'Kalan Süre',
        ratio:'Oran',
        added:'Eklendi',
        all:'Tümü',
        downloading:'İndiriliyor',
        seeding:'Paylaşılıyor',
        completed:'Tamamlandı',
        paused:'Duraklatıldı',
        queued:'Sırada',
        error:'Hata',
        general:'Genel',
        files:'Dosyalar',
        peerList:'Eşler',
        trackers:'Tracker\'lar',
        info:'Bilgi',
        noTorrents:'Henüz torrent yok',
        addMagnet:'Magnet link yapıştır...',
        selectFile:'.torrent dosyası seç',
        deleteConfirm:'Bu torrenti kaldırmak istediğinize emin misiniz?',
        yes:'Evet',
        totalDown:'Toplam İndirme',
        totalUp:'Toplam Yükleme',
        downloadPath:'İndirme Yolu',
        maxDown:'Maks İndirme (KB/s)',
        maxUp:'Maks Yükleme (KB/s)',
        unlimited:'Sınırsız',
        save:'Kaydet',
        port:'Port',
        dht:'DHT',
        fileName:'Dosya Adı',
        fileSize:'Boyut',
        fileProg:'İlerleme',
        peerAddr:'Adres',
        peerClient:'İstemci',
        peerDown:'İndirme',
        peerUp:'Yükleme',
        trackerUrl:'Tracker URL',
        trackerStatus:'Durum',
        hash:'Info Hash',
        created:'Oluşturulma',
        comment:'Açıklama',
        creator:'Oluşturan',
        private:'Özel',
        pieces:'Parça',
        pieceLen:'Parça Boyutu',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'veya',
        startAll:'Tümünü Başlat',
        pauseAll:'Tümünü Duraklat',
        connected:'Bağlı',
        disconnected:'Bağlantı kesildi',
        notInstalled:'WebTorrent sunucuda kurulu değil. npm install webtorrent yapın.'
      },
      en: {
        title:'Torrent',
        addTorrent:'Add Torrent',
        magnetLink:'Magnet Link',
        torrentFile:'.torrent File',
        add:'Add',
        cancel:'Cancel',
        pause:'Pause',
        resume:'Resume',
        remove:'Remove',
        removeData:'Delete with data',
        settings:'Settings',
        name:'Name',
        size:'Size',
        progress:'Progress',
        status:'Status',
        downSpeed:'Download',
        upSpeed:'Upload',
        peers:'Peers',
        seeds:'Seeds',
        eta:'ETA',
        ratio:'Ratio',
        added:'Added',
        all:'All',
        downloading:'Downloading',
        seeding:'Seeding',
        completed:'Completed',
        paused:'Paused',
        queued:'Queued',
        error:'Error',
        general:'General',
        files:'Files',
        peerList:'Peers',
        trackers:'Trackers',
        info:'Info',
        noTorrents:'No torrents yet',
        addMagnet:'Paste magnet link...',
        selectFile:'Select .torrent file',
        deleteConfirm:'Are you sure you want to remove this torrent?',
        yes:'Yes',
        totalDown:'Total Download',
        totalUp:'Total Upload',
        downloadPath:'Download Path',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unlimited',
        save:'Save',
        port:'Port',
        dht:'DHT',
        fileName:'File Name',
        fileSize:'Size',
        fileProg:'Progress',
        peerAddr:'Address',
        peerClient:'Client',
        peerDown:'Download',
        peerUp:'Upload',
        trackerUrl:'Tracker URL',
        trackerStatus:'Status',
        hash:'Info Hash',
        created:'Created',
        comment:'Comment',
        creator:'Creator',
        private:'Private',
        pieces:'Pieces',
        pieceLen:'Piece Size',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'or',
        startAll:'Start All',
        pauseAll:'Pause All',
        connected:'Connected',
        disconnected:'Disconnected',
        notInstalled:'WebTorrent not installed on server. Run npm install webtorrent.'
      },
      de: {
        title:'Torrent',
        addTorrent:'Torrent hinzufügen',
        magnetLink:'Magnet-Link',
        torrentFile:'.torrent-Datei',
        add:'Hinzufügen',
        cancel:'Abbrechen',
        pause:'Pause',
        resume:'Fortsetzen',
        remove:'Entfernen',
        removeData:'Mit Daten löschen',
        settings:'Einstellungen',
        name:'Name',
        size:'Größe',
        progress:'Fortschritt',
        status:'Status',
        downSpeed:'Download',
        upSpeed:'Upload',
        peers:'Peers',
        seeds:'Seeds',
        eta:'Verbleibend',
        ratio:'Verhältnis',
        added:'Hinzugefügt',
        all:'Alle',
        downloading:'Wird heruntergeladen',
        seeding:'Wird geteilt',
        completed:'Abgeschlossen',
        paused:'Pausiert',
        queued:'In Warteschlange',
        error:'Fehler',
        general:'Allgemein',
        files:'Dateien',
        peerList:'Peers',
        trackers:'Tracker',
        info:'Info',
        noTorrents:'Noch keine Torrents',
        addMagnet:'Magnet-Link einfügen...',
        selectFile:'.torrent-Datei auswählen',
        deleteConfirm:'Möchten Sie diesen Torrent wirklich entfernen?',
        yes:'Ja',
        totalDown:'Gesamt-Download',
        totalUp:'Gesamt-Upload',
        downloadPath:'Download-Pfad',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unbegrenzt',
        save:'Speichern',
        port:'Port',
        dht:'DHT',
        fileName:'Dateiname',
        fileSize:'Größe',
        fileProg:'Fortschritt',
        peerAddr:'Adresse',
        peerClient:'Client',
        peerDown:'Download',
        peerUp:'Upload',
        trackerUrl:'Tracker-URL',
        trackerStatus:'Status',
        hash:'Info-Hash',
        created:'Erstellt',
        comment:'Kommentar',
        creator:'Ersteller',
        private:'Privat',
        pieces:'Teile',
        pieceLen:'Teilgröße',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'oder',
        startAll:'Alle starten',
        pauseAll:'Alle pausieren',
        connected:'Verbunden',
        disconnected:'Getrennt',
        notInstalled:'WebTorrent ist nicht installiert. Führen Sie npm install webtorrent aus.'
      },
      fr: {
        title:'Torrent',
        addTorrent:'Ajouter un Torrent',
        magnetLink:'Lien Magnet',
        torrentFile:'Fichier .torrent',
        add:'Ajouter',
        cancel:'Annuler',
        pause:'Pause',
        resume:'Reprendre',
        remove:'Supprimer',
        removeData:'Supprimer avec les données',
        settings:'Paramètres',
        name:'Nom',
        size:'Taille',
        progress:'Progression',
        status:'Statut',
        downSpeed:'Téléchargement',
        upSpeed:'Upload',
        peers:'Pairs',
        seeds:'Seeds',
        eta:'Temps restant',
        ratio:'Ratio',
        added:'Ajouté',
        all:'Tous',
        downloading:'En téléchargement',
        seeding:'En partage',
        completed:'Terminé',
        paused:'En pause',
        queued:'En attente',
        error:'Erreur',
        general:'Général',
        files:'Fichiers',
        peerList:'Pairs',
        trackers:'Trackers',
        info:'Info',
        noTorrents:'Aucun torrent',
        addMagnet:'Collez un lien magnet...',
        selectFile:'Sélectionner un fichier .torrent',
        deleteConfirm:'Êtes-vous sûr de vouloir supprimer ce torrent ?',
        yes:'Oui',
        totalDown:'Total téléchargé',
        totalUp:'Total uploadé',
        downloadPath:'Chemin de téléchargement',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Illimité',
        save:'Enregistrer',
        port:'Port',
        dht:'DHT',
        fileName:'Nom du fichier',
        fileSize:'Taille',
        fileProg:'Progression',
        peerAddr:'Adresse',
        peerClient:'Client',
        peerDown:'Téléchargement',
        peerUp:'Upload',
        trackerUrl:'URL du Tracker',
        trackerStatus:'Statut',
        hash:'Info Hash',
        created:'Créé',
        comment:'Commentaire',
        creator:'Créateur',
        private:'Privé',
        pieces:'Pièces',
        pieceLen:'Taille de pièce',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'ou',
        startAll:'Tout démarrer',
        pauseAll:'Tout mettre en pause',
        connected:'Connecté',
        disconnected:'Déconnecté',
        notInstalled:'WebTorrent non installé sur le serveur. Exécutez npm install webtorrent.'
      },
      es: {
        title:'Torrent',
        addTorrent:'Agregar Torrent',
        magnetLink:'Enlace Magnet',
        torrentFile:'Archivo .torrent',
        add:'Agregar',
        cancel:'Cancelar',
        pause:'Pausar',
        resume:'Reanudar',
        remove:'Eliminar',
        removeData:'Eliminar con datos',
        settings:'Ajustes',
        name:'Nombre',
        size:'Tamaño',
        progress:'Progreso',
        status:'Estado',
        downSpeed:'Descarga',
        upSpeed:'Subida',
        peers:'Pares',
        seeds:'Seeds',
        eta:'Tiempo restante',
        ratio:'Ratio',
        added:'Agregado',
        all:'Todos',
        downloading:'Descargando',
        seeding:'Compartiendo',
        completed:'Completado',
        paused:'Pausado',
        queued:'En cola',
        error:'Error',
        general:'General',
        files:'Archivos',
        peerList:'Pares',
        trackers:'Trackers',
        info:'Info',
        noTorrents:'Sin torrents',
        addMagnet:'Pega un enlace magnet...',
        selectFile:'Seleccionar archivo .torrent',
        deleteConfirm:'¿Estás seguro de que quieres eliminar este torrent?',
        yes:'Sí',
        totalDown:'Descarga total',
        totalUp:'Subida total',
        downloadPath:'Ruta de descarga',
        maxDown:'Máx Descarga (KB/s)',
        maxUp:'Máx Subida (KB/s)',
        unlimited:'Ilimitado',
        save:'Guardar',
        port:'Puerto',
        dht:'DHT',
        fileName:'Nombre de archivo',
        fileSize:'Tamaño',
        fileProg:'Progreso',
        peerAddr:'Dirección',
        peerClient:'Cliente',
        peerDown:'Descarga',
        peerUp:'Subida',
        trackerUrl:'URL del Tracker',
        trackerStatus:'Estado',
        hash:'Info Hash',
        created:'Creado',
        comment:'Comentario',
        creator:'Creador',
        private:'Privado',
        pieces:'Piezas',
        pieceLen:'Tamaño de pieza',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'o',
        startAll:'Iniciar todos',
        pauseAll:'Pausar todos',
        connected:'Conectado',
        disconnected:'Desconectado',
        notInstalled:'WebTorrent no está instalado en el servidor. Ejecute npm install webtorrent.'
      },
      ru: {
        title:'Торрент',
        addTorrent:'Добавить торрент',
        magnetLink:'Magnet-ссылка',
        torrentFile:'.torrent файл',
        add:'Добавить',
        cancel:'Отмена',
        pause:'Пауза',
        resume:'Продолжить',
        remove:'Удалить',
        removeData:'Удалить с данными',
        settings:'Настройки',
        name:'Имя',
        size:'Размер',
        progress:'Прогресс',
        status:'Статус',
        downSpeed:'Загрузка',
        upSpeed:'Отдача',
        peers:'Пиры',
        seeds:'Сиды',
        eta:'Осталось',
        ratio:'Рейтинг',
        added:'Добавлен',
        all:'Все',
        downloading:'Загружается',
        seeding:'Раздаётся',
        completed:'Завершён',
        paused:'На паузе',
        queued:'В очереди',
        error:'Ошибка',
        general:'Общие',
        files:'Файлы',
        peerList:'Пиры',
        trackers:'Трекеры',
        info:'Инфо',
        noTorrents:'Нет торрентов',
        addMagnet:'Вставьте magnet-ссылку...',
        selectFile:'Выберите .torrent файл',
        deleteConfirm:'Вы уверены, что хотите удалить этот торрент?',
        yes:'Да',
        totalDown:'Всего загружено',
        totalUp:'Всего отдано',
        downloadPath:'Путь загрузки',
        maxDown:'Макс загрузка (КБ/с)',
        maxUp:'Макс отдача (КБ/с)',
        unlimited:'Без ограничений',
        save:'Сохранить',
        port:'Порт',
        dht:'DHT',
        fileName:'Имя файла',
        fileSize:'Размер',
        fileProg:'Прогресс',
        peerAddr:'Адрес',
        peerClient:'Клиент',
        peerDown:'Загрузка',
        peerUp:'Отдача',
        trackerUrl:'URL трекера',
        trackerStatus:'Статус',
        hash:'Инфо-хеш',
        created:'Создан',
        comment:'Комментарий',
        creator:'Создатель',
        private:'Приватный',
        pieces:'Части',
        pieceLen:'Размер части',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'или',
        startAll:'Запустить все',
        pauseAll:'Приостановить все',
        connected:'Подключён',
        disconnected:'Отключён',
        notInstalled:'WebTorrent не установлен на сервере. Выполните npm install webtorrent.'
      },
      zh: {
        title:'Torrent',
        addTorrent:'添加Torrent',
        magnetLink:'磁力链接',
        torrentFile:'Torrent文件',
        add:'添加',
        cancel:'取消',
        pause:'暂停',
        resume:'继续',
        remove:'移除',
        removeData:'移除及删除数据',
        settings:'设置',
        name:'名称',
        size:'大小',
        progress:'进度',
        status:'状态',
        downSpeed:'下载速度',
        upSpeed:'上传速度',
        peers:'节点',
        seeds:'做种',
        eta:'预计剩余时间',
        ratio:'比率',
        added:'已添加',
        all:'全部',
        downloading:'下载中',
        seeding:'做种中',
        completed:'已完成',
        paused:'已暂停',
        queued:'排队中',
        error:'错误',
        general:'常规',
        files:'文件',
        peerList:'节点列表',
        trackers:'Tracker',
        info:'信息',
        noTorrents:'没有Torrent',
        addMagnet:'添加磁力链接',
        selectFile:'选择文件',
        deleteConfirm:'确认删除？',
        yes:'是',
        totalDown:'总下载',
        totalUp:'总上传',
        downloadPath:'下载路径',
        maxDown:'最大下载速度',
        maxUp:'最大上传速度',
        unlimited:'无限制',
        save:'保存',
        port:'端口',
        dht:'DHT',
        fileName:'文件名',
        fileSize:'文件大小',
        fileProg:'文件进度',
        peerAddr:'节点地址',
        peerClient:'客户端',
        peerDown:'下载速度',
        peerUp:'上传速度',
        trackerUrl:'Tracker地址',
        trackerStatus:'Tracker状态',
        hash:'哈希值',
        created:'创建时间',
        comment:'备注',
        creator:'创建者',
        private:'私有',
        pieces:'分片',
        pieceLen:'分片大小',
        magnetPlaceholder:'输入磁力链接...',
        magnet:'磁力',
        urn:'URN',
        btih:'BTIH',
        or:'或',
        startAll:'全部开始',
        pauseAll:'全部暂停',
        connected:'已连接',
        disconnected:'已断开',
        notInstalled:'未安装'
      },
      ja: {
        title:'Torrent',
        addTorrent:'Torrent追加',
        magnetLink:'マグネットリンク',
        torrentFile:'Torrentファイル',
        add:'追加',
        cancel:'キャンセル',
        pause:'一時停止',
        resume:'再開',
        remove:'削除',
        removeData:'データも削除',
        settings:'設定',
        name:'名前',
        size:'サイズ',
        progress:'進捗',
        status:'状態',
        downSpeed:'ダウンロード速度',
        upSpeed:'アップロード速度',
        peers:'ピア',
        seeds:'シード',
        eta:'残り時間',
        ratio:'レシオ',
        added:'追加済',
        all:'すべて',
        downloading:'ダウンロード中',
        seeding:'シード中',
        completed:'完了',
        paused:'一時停止中',
        queued:'待機中',
        error:'エラー',
        general:'一般',
        files:'ファイル',
        peerList:'ピア一覧',
        trackers:'トラッカー',
        info:'情報',
        noTorrents:'Torrentなし',
        addMagnet:'マグネット追加',
        selectFile:'ファイル選択',
        deleteConfirm:'削除しますか？',
        yes:'はい',
        totalDown:'総ダウンロード',
        totalUp:'総アップロード',
        downloadPath:'ダウンロード先',
        maxDown:'最大ダウンロード速度',
        maxUp:'最大アップロード速度',
        unlimited:'無制限',
        save:'保存',
        port:'ポート',
        dht:'DHT',
        fileName:'ファイル名',
        fileSize:'ファイルサイズ',
        fileProg:'ファイル進捗',
        peerAddr:'ピアアドレス',
        peerClient:'クライアント',
        peerDown:'ダウンロード速度',
        peerUp:'アップロード速度',
        trackerUrl:'トラッカーURL',
        trackerStatus:'トラッカー状態',
        hash:'ハッシュ',
        created:'作成日',
        comment:'コメント',
        creator:'作成者',
        private:'プライベート',
        pieces:'ピース',
        pieceLen:'ピースサイズ',
        magnetPlaceholder:'マグネットリンクを入力...',
        magnet:'マグネット',
        urn:'URN',
        btih:'BTIH',
        or:'または',
        startAll:'すべて開始',
        pauseAll:'すべて一時停止',
        connected:'接続済',
        disconnected:'切断',
        notInstalled:'未インストール'
      },
      it: {
        title:'Torrent',
        addTorrent:'Aggiungi Torrent',
        magnetLink:'Link magnet',
        torrentFile:'File Torrent',
        add:'Aggiungi',
        cancel:'Annulla',
        pause:'Pausa',
        resume:'Riprendi',
        remove:'Rimuovi',
        removeData:'Rimuovi con dati',
        settings:'Impostazioni',
        name:'Nome',
        size:'Dimensione',
        progress:'Progresso',
        status:'Stato',
        downSpeed:'Velocità download',
        upSpeed:'Velocità upload',
        peers:'Peer',
        seeds:'Seed',
        eta:'Tempo stimato',
        ratio:'Rapporto',
        added:'Aggiunto',
        all:'Tutti',
        downloading:'Download in corso',
        seeding:'In seed',
        completed:'Completato',
        paused:'In pausa',
        queued:'In coda',
        error:'Errore',
        general:'Generale',
        files:'File',
        peerList:'Lista peer',
        trackers:'Tracker',
        info:'Informazioni',
        noTorrents:'Nessun Torrent',
        addMagnet:'Aggiungi magnet',
        selectFile:'Seleziona file',
        deleteConfirm:'Confermi eliminazione?',
        yes:'Sì',
        totalDown:'Download totale',
        totalUp:'Upload totale',
        downloadPath:'Percorso download',
        maxDown:'Velocità max download',
        maxUp:'Velocità max upload',
        unlimited:'Illimitato',
        save:'Salva',
        port:'Porta',
        dht:'DHT',
        fileName:'Nome file',
        fileSize:'Dimensione file',
        fileProg:'Progresso file',
        peerAddr:'Indirizzo peer',
        peerClient:'Client',
        peerDown:'Velocità download',
        peerUp:'Velocità upload',
        trackerUrl:'URL tracker',
        trackerStatus:'Stato tracker',
        hash:'Hash',
        created:'Creato',
        comment:'Commento',
        creator:'Creatore',
        private:'Privato',
        pieces:'Pezzi',
        pieceLen:'Dimensione pezzo',
        magnetPlaceholder:'Inserisci link magnet...',
        magnet:'Magnet',
        urn:'URN',
        btih:'BTIH',
        or:'o',
        startAll:'Avvia tutti',
        pauseAll:'Pausa tutti',
        connected:'Connesso',
        disconnected:'Disconnesso',
        notInstalled:'Non installato'
      },
      ar: {
        title:'تورنت',
        addTorrent:'Add Torrent',
        magnetLink:'Magnet Link',
        torrentFile:'.torrent File',
        add:'إضافة',
        cancel:'إلغاء',
        pause:'إيقاف',
        resume:'استئناف',
        remove:'إزالة',
        removeData:'Delete with data',
        settings:'الإعدادات',
        name:'الاسم',
        size:'الحجم',
        progress:'Progress',
        status:'الحالة',
        downSpeed:'تنزيل',
        upSpeed:'رفع',
        peers:'Peers',
        seeds:'Seeds',
        eta:'ETA',
        ratio:'Ratio',
        added:'Added',
        all:'الكل',
        downloading:'Downloading',
        seeding:'Seeding',
        completed:'Completed',
        paused:'Paused',
        queued:'Queued',
        error:'خطأ',
        general:'General',
        files:'الملفات',
        peerList:'Peers',
        trackers:'Trackers',
        info:'معلومات',
        noTorrents:'No torrents yet',
        addMagnet:'Paste magnet link...',
        selectFile:'Select .torrent file',
        deleteConfirm:'Are you sure you want to remove this torrent?',
        yes:'نعم',
        totalDown:'Total Download',
        totalUp:'Total Upload',
        downloadPath:'Download Path',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unlimited',
        save:'حفظ',
        port:'المنفذ',
        dht:'DHT',
        fileName:'اسم الملف',
        fileSize:'الحجم',
        fileProg:'Progress',
        peerAddr:'Address',
        peerClient:'Client',
        peerDown:'تنزيل',
        peerUp:'رفع',
        trackerUrl:'Tracker URL',
        trackerStatus:'الحالة',
        hash:'Info Hash',
        created:'تاريخ الإنشاء',
        comment:'Comment',
        creator:'Creator',
        private:'Private',
        pieces:'Pieces',
        pieceLen:'Piece Size',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'or',
        startAll:'Start All',
        pauseAll:'Pause All',
        connected:'متصل',
        disconnected:'غير متصل',
        notInstalled:'غير مثبت'
      },
      ko: {
        title:'토렌트',
        addTorrent:'Add Torrent',
        magnetLink:'Magnet Link',
        torrentFile:'.torrent File',
        add:'추가',
        cancel:'취소',
        pause:'Pause',
        resume:'재개',
        remove:'제거',
        removeData:'Delete with data',
        settings:'설정',
        name:'이름',
        size:'크기',
        progress:'Progress',
        status:'상태',
        downSpeed:'다운로드',
        upSpeed:'업로드',
        peers:'Peers',
        seeds:'Seeds',
        eta:'ETA',
        ratio:'Ratio',
        added:'Added',
        all:'전체',
        downloading:'Downloading',
        seeding:'Seeding',
        completed:'Completed',
        paused:'Paused',
        queued:'Queued',
        error:'오류',
        general:'General',
        files:'파일',
        peerList:'Peers',
        trackers:'Trackers',
        info:'정보',
        noTorrents:'No torrents yet',
        addMagnet:'Paste magnet link...',
        selectFile:'Select .torrent file',
        deleteConfirm:'Are you sure you want to remove this torrent?',
        yes:'예',
        totalDown:'Total Download',
        totalUp:'Total Upload',
        downloadPath:'Download Path',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unlimited',
        save:'저장',
        port:'포트',
        dht:'DHT',
        fileName:'파일 이름',
        fileSize:'크기',
        fileProg:'Progress',
        peerAddr:'Address',
        peerClient:'Client',
        peerDown:'다운로드',
        peerUp:'업로드',
        trackerUrl:'Tracker URL',
        trackerStatus:'상태',
        hash:'Info Hash',
        created:'생성일',
        comment:'Comment',
        creator:'Creator',
        private:'Private',
        pieces:'Pieces',
        pieceLen:'Piece Size',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'or',
        startAll:'Start All',
        pauseAll:'Pause All',
        connected:'연결됨',
        disconnected:'연결 끊김',
        notInstalled:'설치되지 않음'
      },
      hi: {
        title:'टोरेंट',
        addTorrent:'Add Torrent',
        magnetLink:'Magnet Link',
        torrentFile:'.torrent File',
        add:'जोड़ें',
        cancel:'रद्द करें',
        pause:'Pause',
        resume:'जारी',
        remove:'हटाएं',
        removeData:'Delete with data',
        settings:'सेटिंग',
        name:'नाम',
        size:'आकार',
        progress:'Progress',
        status:'स्थिति',
        downSpeed:'डाउनलोड',
        upSpeed:'अपलोड',
        peers:'Peers',
        seeds:'Seeds',
        eta:'ETA',
        ratio:'Ratio',
        added:'Added',
        all:'सभी',
        downloading:'Downloading',
        seeding:'Seeding',
        completed:'Completed',
        paused:'Paused',
        queued:'Queued',
        error:'त्रुटि',
        general:'General',
        files:'फ़ाइलें',
        peerList:'Peers',
        trackers:'Trackers',
        info:'जानकारी',
        noTorrents:'No torrents yet',
        addMagnet:'Paste magnet link...',
        selectFile:'Select .torrent file',
        deleteConfirm:'Are you sure you want to remove this torrent?',
        yes:'हाँ',
        totalDown:'Total Download',
        totalUp:'Total Upload',
        downloadPath:'Download Path',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unlimited',
        save:'सहेजें',
        port:'पोर्ट',
        dht:'DHT',
        fileName:'फ़ाइल नाम',
        fileSize:'आकार',
        fileProg:'Progress',
        peerAddr:'Address',
        peerClient:'Client',
        peerDown:'डाउनलोड',
        peerUp:'अपलोड',
        trackerUrl:'Tracker URL',
        trackerStatus:'स्थिति',
        hash:'Info Hash',
        created:'बनाया गया',
        comment:'Comment',
        creator:'Creator',
        private:'Private',
        pieces:'Pieces',
        pieceLen:'Piece Size',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'or',
        startAll:'Start All',
        pauseAll:'Pause All',
        connected:'कनेक्टेड',
        disconnected:'डिस्कनेक्ट',
        notInstalled:'इंस्टॉल नहीं'
      },
      pt: {
        title:'Torrent',
        addTorrent:'Add Torrent',
        magnetLink:'Magnet Link',
        torrentFile:'.torrent File',
        add:'Adicionar',
        cancel:'Cancelar',
        pause:'Pause',
        resume:'Continuar',
        remove:'Remover',
        removeData:'Delete with data',
        settings:'Configurações',
        name:'Nome',
        size:'Porte',
        progress:'Progress',
        status:'Status',
        downSpeed:'Baixar',
        upSpeed:'Enviar',
        peers:'Peers',
        seeds:'Seeds',
        eta:'ETA',
        ratio:'Ratio',
        added:'Added',
        all:'Todas',
        downloading:'Downloading',
        seeding:'Seeding',
        completed:'Completed',
        paused:'Paused',
        queued:'Queued',
        error:'Erro',
        general:'General',
        files:'Arquivos',
        peerList:'Peers',
        trackers:'Trackers',
        info:'Info',
        noTorrents:'No torrents yet',
        addMagnet:'Paste magnet link...',
        selectFile:'Select .torrent file',
        deleteConfirm:'Are you sure you want to remove this torrent?',
        yes:'Sim',
        totalDown:'Total Download',
        totalUp:'Total Upload',
        downloadPath:'Download Path',
        maxDown:'Max Download (KB/s)',
        maxUp:'Max Upload (KB/s)',
        unlimited:'Unlimited',
        save:'Salvar',
        port:'Porta',
        dht:'DHT',
        fileName:'Nome do arquivo',
        fileSize:'Porte',
        fileProg:'Progress',
        peerAddr:'Address',
        peerClient:'Client',
        peerDown:'Baixar',
        peerUp:'Enviar',
        trackerUrl:'Tracker URL',
        trackerStatus:'Status',
        hash:'Info Hash',
        created:'Criado',
        comment:'Comment',
        creator:'Creator',
        private:'Private',
        pieces:'Pieces',
        pieceLen:'Piece Size',
        magnetPlaceholder:'magnet:?xt=urn:btih:...',
        or:'or',
        startAll:'Start All',
        pauseAll:'Pause All',
        connected:'Conectado',
        disconnected:'Desconectado',
        notInstalled:'Nao instalado'
      }
  };

    function getLocale() { return localStorage.getItem('sys_locale') || 'tr'; }
    var locale = ref(getLocale());
    var t = function(k) { return (LANGS[locale.value] && LANGS[locale.value][k]) || LANGS.en[k] || k; };
    function onLocaleChanged(e) { locale.value = e.detail || getLocale(); }
    var isMounted = false;

    /* ── Auth ── */
    function getToken() { return localStorage.getItem('auth_token'); }
    function authHeaders() { return { Authorization: 'Bearer ' + getToken(), 'Content-Type': 'application/json' }; }

    /* ── State ── */
    var torrents = ref([]);
    var selectedHash = ref('');
    var filter = ref('all');
    var addDialogVisible = ref(false);
    var settingsDialogVisible = ref(false);
    var magnetInput = ref('');
    var detailTab = ref('general');
    var wsConnected = ref(false);
    var serverReady = ref(true);
    var ws = null;

    /* settings */
    var stDownPath = ref('downloads');
    var stMaxDown = ref(0);
    var stMaxUp = ref(0);

    /* ── Computed ── */
    var filteredTorrents = computed(function() {
      if (filter.value === 'all') return torrents.value;
      return torrents.value.filter(function(t) { return t.status === filter.value; });
    });

    var selectedTorrent = computed(function() {
      return torrents.value.find(function(t) { return t.infoHash === selectedHash.value; }) || null;
    });

    var totalDownSpeed = computed(function() {
      return torrents.value.reduce(function(s, t) { return s + (t.downloadSpeed || 0); }, 0);
    });

    var totalUpSpeed = computed(function() {
      return torrents.value.reduce(function(s, t) { return s + (t.uploadSpeed || 0); }, 0);
    });

    var filterCounts = computed(function() {
      var c = { all: torrents.value.length, downloading: 0, seeding: 0, completed: 0, paused: 0, error: 0 };
      torrents.value.forEach(function(t) { if (c[t.status] !== undefined) c[t.status]++; });
      return c;
    });

    /* ── Formatting ── */
    function formatBytes(b) {
      if (!b || b === 0) return '0 B';
      var units = ['B','KB','MB','GB','TB'];
      var i = Math.floor(Math.log(b) / Math.log(1024));
      return (b / Math.pow(1024, i)).toFixed(i > 0 ? 1 : 0) + ' ' + units[i];
    }

    function formatSpeed(bps) {
      if (!bps || bps === 0) return '0 B/s';
      return formatBytes(bps) + '/s';
    }

    function formatEta(seconds) {
      if (!seconds || seconds <= 0 || !isFinite(seconds)) return '∞';
      var h = Math.floor(seconds / 3600);
      var m = Math.floor((seconds % 3600) / 60);
      var s = Math.floor(seconds % 60);
      if (h > 0) return h + 'h ' + m + 'm';
      if (m > 0) return m + 'm ' + s + 's';
      return s + 's';
    }

    function statusType(st) {
      var map = { downloading: 'primary', seeding: 'success', completed: 'success', paused: 'warning', error: 'danger', queued: 'info' };
      return map[st] || 'info';
    }

    function statusIcon(st) {
      var map = { downloading: '⬇️', seeding: '⬆️', completed: '✅', paused: '⏸️', error: '❌', queued: '⏳' };
      return map[st] || '❓';
    }

    /* ── WebSocket ── */
    function connectWS() {
      var proto = location.protocol === 'https:' ? 'wss' : 'ws';
      ws = new WebSocket(proto + '://' + location.host + '/ws?token=' + encodeURIComponent(getToken()));
      ws.onopen = function() {
        wsConnected.value = true;
        ws.send(JSON.stringify({ type: 'torrent-subscribe' }));
      };
      ws.onmessage = function(ev) {
        try {
          var msg = JSON.parse(ev.data);
          if (msg.type === 'torrent-list' || msg.type === 'torrent-progress') {
            if (Array.isArray(msg.data)) {
              torrents.value = msg.data;
            }
          } else if (msg.type === 'torrent-added') {
            ElMessage.success(t('added') + ': ' + (msg.data.name || ''));
          } else if (msg.type === 'torrent-error') {
            ElMessage.error(msg.data.error || t('error'));
          } else if (msg.type === 'torrent-not-installed') {
            serverReady.value = false;
          }
        } catch(e) {}
      };
      ws.onclose = function() {
        wsConnected.value = false;
        setTimeout(function() { if (isMounted) connectWS(); }, 3000);
      };
      ws.onerror = function() { ws.close(); };
    }

    function sendWS(obj) {
      if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(obj));
    }

    /* ── Actions ── */
    function addMagnet() {
      var link = magnetInput.value.trim();
      if (!link) return;
      sendWS({ type: 'torrent-add', data: { magnet: link, path: stDownPath.value } });
      magnetInput.value = '';
      addDialogVisible.value = false;
    }

    function uploadTorrentFile() {
      var input = document.createElement('input');
      input.type = 'file';
      input.accept = '.torrent';
      input.onchange = function(e) {
        var file = e.target.files[0];
        if (!file) return;
        var reader = new FileReader();
        reader.onload = function(ev) {
          var base64 = btoa(String.fromCharCode.apply(null, new Uint8Array(ev.target.result)));
          sendWS({ type: 'torrent-add', data: { torrentBase64: base64, name: file.name, path: stDownPath.value } });
          addDialogVisible.value = false;
        };
        reader.readAsArrayBuffer(file);
      };
      input.click();
    }

    function pauseTorrent(hash) { sendWS({ type: 'torrent-pause', data: { infoHash: hash } }); }
    function resumeTorrent(hash) { sendWS({ type: 'torrent-resume', data: { infoHash: hash } }); }

    async function removeTorrent(hash, deleteData) {
      try {
        await ElMessageBox.confirm(t('deleteConfirm'), t('remove'), {
          type: 'warning', confirmButtonText: t('yes'), cancelButtonText: t('cancel')
        });
      } catch { return; }
      sendWS({ type: 'torrent-remove', data: { infoHash: hash, deleteData: !!deleteData } });
      if (selectedHash.value === hash) selectedHash.value = '';
    }

    function startAll() { sendWS({ type: 'torrent-start-all' }); }
    function pauseAll() { sendWS({ type: 'torrent-pause-all' }); }

    function selectTorrent(row) { selectedHash.value = row.infoHash; }

    function saveSettings() {
      sendWS({ type: 'torrent-settings', data: { downloadPath: stDownPath.value, maxDownloadSpeed: stMaxDown.value, maxUploadSpeed: stMaxUp.value } });
      settingsDialogVisible.value = false;
      ElMessage.success(t('save'));
    }

    /* ── Row class ── */
    function tableRowClass(row) {
      return row.row.infoHash === selectedHash.value ? 'tor-row-selected' : '';
    }

    /* ── Lifecycle ── */
    onMounted(function() {
      isMounted = true;
      connectWS();
      window.addEventListener('locale-changed', onLocaleChanged);
    });

    onUnmounted(function() {
      isMounted = false;
      window.removeEventListener('locale-changed', onLocaleChanged)
      if (ws) { sendWS({ type: 'torrent-unsubscribe' }); ws.close(); ws = null; }
    });

    return {
      locale, t, torrents, selectedHash, filter, addDialogVisible, settingsDialogVisible,
      magnetInput, detailTab, wsConnected, serverReady,
      filteredTorrents, selectedTorrent, totalDownSpeed, totalUpSpeed, filterCounts,
      formatBytes, formatSpeed, formatEta, statusType, statusIcon,
      addMagnet, uploadTorrentFile, pauseTorrent, resumeTorrent, removeTorrent,
      startAll, pauseAll, selectTorrent, saveSettings, tableRowClass,
      stDownPath, stMaxDown, stMaxUp
    };
  }
})
